language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install tox-travis
script:
  - tox
  - py.test -vv --cov=esqb --cov-report term --cov-report term --cov-report html
#deploy:
#  provider: pypi
#  user: "Your username"
#  password: "Your password"
#  on:
#    tags: true
#    branch: master
