language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements_dev.txt
  - pip install tox-travis
script:
  - tox
#deploy:
#  provider: pypi
#  user: "Your username"
#  password: "Your password"
#  on:
#    tags: true
#    branch: master
